// Code generated by ifacemaker; DO NOT EDIT.

package api

import (
	"net/http"
)

// ifacemaker -f actor.go -f auth.go -f film.go -f http.go -s Handler -i HandlerInterface -p api -o ../handler.go
type HandlerInterface interface {
	CreateActor() http.HandlerFunc
	GetActors() http.HandlerFunc
	UpdateActor() http.HandlerFunc
	DeleteActor() http.HandlerFunc
	SignIn() http.HandlerFunc
	SignUp() http.HandlerFunc
	CreateFilm() http.HandlerFunc
	GetFilms() http.HandlerFunc
	UpdateFilm() http.HandlerFunc
	DeleteFilm() http.HandlerFunc
	SearchFilm() http.HandlerFunc
}
