// Code generated by ifacemaker; DO NOT EDIT.

package api

import (
	api_models "vk_test_task/internal/api/models"

	_ "github.com/jackc/pgx/v5/stdlib"
)

// ifacemaker -f actor.go -f auth.go -f film.go -f postgres.go -s Repository -i RepositoryInterface -p api -o ../repository.go -y
type RepositoryInterface interface {
	CreateActor(params api_models.CreateActorParams) error
	GetActors() (api_models.GetActorsResponse, error)
	UpdateActor(params api_models.UpdateActorParams) error
	DeleteActor(actorId string) error
	SignIn(login string) (api_models.SignInRepositoryResponse, error)
	SignUp(login, hashPassword, userId string) error
	CreateFilm(params api_models.CreateFilmParams) error
	GetFilms(params api_models.GetFilmsParams) (api_models.GetFilmsResponse, error)
	UpdateFilm(params api_models.UpdateFilmParams) error
	DeleteFilm(filmId string) error
	SearchFilmByName(name string) (api_models.SearchFilmResponse, error)
	SearchFilmByActorName(actorName string) (api_models.SearchFilmResponse, error)
}
