// Code generated by ifacemaker; DO NOT EDIT.

package api

// ifacemaker -f ./repository/redis/redis.go -s Repository -i TokenRepositoryInterface -p api -o ./tokenRepository.go
type TokenRepositoryInterface interface {
	CreateAccessToken(userId string, isAdmin bool) (string, int64, error)
	CreateRefreshToken(isAdmin bool) (string, int64, error)
	VerifyRefreshToken(userId string, tokenString string) (bool, error)
	UpdateAccessToken(userId string, refreshToken string) (string, int64, error)
	CreateTokensPair(userId string, isAdmin bool) (string, string, int64, error)
}
