// Code generated by ifacemaker; DO NOT EDIT.

package api

import (
	api_models "vk_test_task/internal/api/models"
)

// ifacemaker -f actor.go -f auth.go -f film.go -f postgres.go -s Repository -i RepositoryInterface -p api -o ../repository.go -y
type UseCaseInterface interface {
	CreateActor(params api_models.CreateActorParams) (string, error)
	GetActors() (api_models.GetActorsResponse, error)
	UpdateActor(params api_models.UpdateActorParams) error
	DeleteActor(params api_models.DeleteActorParams) error
	SignIn(params api_models.AuthParams) (api_models.SignInUseCaseResponse, error)
	SignUp(params api_models.AuthParams) error
	CreateFilm(params api_models.CreateFilmParams) (string, error)
	GetFilms(params api_models.GetFilmsParams) (api_models.GetFilmsResponse, error)
	UpdateFilm(params api_models.UpdateFilmParams) error
	DeleteFilm(params api_models.DeleteFilmParams) error
	SearchFilm(params api_models.SearchFilmParams) (api_models.SearchFilmResponse, error)
}
